# Generated by Django 2.2.6 on 2020-03-16 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0002_auto_20200316_1129'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Editors',
            new_name='Editor',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='editors',
            new_name='editor',
        ),
    ]
